# Generated by Django 2.2.12 on 2020-10-27 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
