# Generated by Django 2.2.12 on 2020-11-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de videollamada'),
        ),
    ]
