# Generated by Django 2.2.12 on 2020-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='state',
            field=models.BooleanField(default=True, verbose_name='state'),
        ),
    ]
