# Generated by Django 2.2.12 on 2020-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='url',
            field=models.URLField(default='http://localhost:9000', verbose_name='Enlace de videollamada'),
        ),
    ]
