# Generated by Django 2.2.12 on 2021-03-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_repetitions', '0001_initial'),
        ('classes', '0003_class_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_repetition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_repetitions.ClassRepetition'),
        ),
    ]
