version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: tip_top_backend_production_django
    container_name: tip_top_backend_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "9000:80"
    external_links:
      - postgres-dev:postgres
    networks:
      - containers_network
    environment:
      - "VIRTUAL_HOST=api.tip-top.pcaingenieria.co"
    command: /start

networks:
  containers_network:
    external: true
