# Generated by Django 2.2.12 on 2020-09-14 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Created At')),
                ('title', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(choices=[('DAYS', 'Days Type'), ('ALLTIME', 'Alltime Type')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SEND', 'Send')], default='PENDING', max_length=30)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('to', models.EmailField(max_length=250, null=True)),
                ('template', models.CharField(max_length=120, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
