# Generated by Django 2.2.12 on 2020-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DAYS', 'Days Type'), ('ALLTIME', 'Alltime Type')], default='EMAIL', max_length=20),
        ),
    ]
