# Generated by Django 2.2.12 on 2020-11-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
